version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8u171-jdk
    steps:
    - checkout
    - run: javac test-resource/DemoClass.java
    - run: make
workflows:
  version: 2
  workflow:
    jobs:
      - build
