# this class should be edited by users to give out basic information for their analysis

apk: "false"
javaClass: "true"
# Use it only for apk
pathToSource: "<Need path to be to the path to source (apk/jar/javaClass)>"
outputPath: "<User prefered output path>"
# Use for java source code file
pathTOClassDirectory: "test-resource"
