# this class should be edited by users to give out basic information for their analysis

apk: "false"
javaClass: "true"
# Use for java byte code file
pathToTargetDirectory: "test-resource"
className: "DemoClass"
methodName: "overloadTester"
outputPath: "<User prefered output path>"
